import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { preload } from "react-dom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  preload("/icons/sprite.svg", { as: "image", fetchPriority: "high" });
  
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
